# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
# https://github.com/bcoe/conventional-release-labels
# https://dev.to/github/how-to-automatically-generate-release-notes-for-your-project-2ng8
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features
      labels:
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
        - enhancement
    - title: Enhancement
      labels:
        - refactor
        - enhancement
    - title: Other Changes
      labels:
        - "*"