#https://freshman.tech/linting-golang/
#https://github.com/TekWizely/pre-commit-golang
repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v0.8.3 # change this to the latest version
    hooks:
    -   id: golangci-lint