#https://dev.to/github/how-to-automatically-generate-release-notes-for-your-project-2ng8
#https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
#https://github.com/bcoe/conventional-release-labels

# add label to pul request based on convectional commit
on:
  pull_request_target:
    types: [ opened, edited ]
name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1