definitions:
  dto.CreateProductRequestDto:
    properties:
      description:
        maxLength: 5000
        minLength: 0
        type: string
      name:
        maxLength: 255
        minLength: 0
        type: string
      price:
        minimum: 0
        type: number
    required:
    - description
    - name
    - price
    type: object
  dto.CreateProductResponseDto:
    properties:
      productId:
        type: string
    type: object
info:
  contact:
    name: Mehdi Hadeli
    url: https://github.com/mehdihadeli
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Create new product item
      parameters:
      - description: Product data
        in: body
        name: CreateProductRequestDto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateProductRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateProductResponseDto'
      summary: Create product
      tags:
      - Products
swagger: "2.0"
