name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Building-Blocks Tests
      run: go test -v ./...
    
    - name: Catalogs Write Service Tests
      working-directory: ./services/catalogs/write_service
      run: go test -v ./...

    - name: Catalogs Read Service Tests
      working-directory: ./services/catalogs/read_service
      run: go test -v ./...

    - name: Order Service Tests
      working-directory: ./services/orders
      run: go test -v ./...
