name: First interaction
on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    name: First interaction

    # https://github.com/actions/first-interaction/issues/10#issuecomment-1278292860
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to go-food-delivery-microservices. Thank you ${{ github.event.pull_request.user.login }} for reporting your first issue. Please check out our [contributor guide](https://github.com/mehdihadeli/go-food-delivery-microservices/blob/main/CONTRIBUTION.md)."
          pr-message: "Thank you ${{ github.event.pull_request.user.login }} for your first pull request to go-food-delivery-microservices repository. Please check out our [contributors guide](https://github.com/mehdihadeli/go-food-delivery-microservices/blob/main/CONTRIBUTION.md)."
